export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const TEACHER_TOTAL_REQUEST = 'TEACHER_TOTAL_REQUEST'
export const TEACHER_TOTAL_SUCCESS = 'TEACHER_TOTAL_SUCCESS'
export const TEACHER_TOTAL_FAIL = 'TEACHER_TOTAL_FAIL'
export const TEACHER_TOTAL_RESET = 'TEACHER_TOTAL_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_RESET = 'USER_DELETE_RESET'

export const USER_CUSTOMER_REGISTER_REQUEST = 'USER_CUSTOMER_REGISTER_REQUEST'
export const USER_CUSTOMER_REGISTER_SUCCESS = 'USER_CUSTOMER_REGISTER_SUCCESS'
export const USER_CUSTOMER_REGISTER_FAIL = 'USER_CUSTOMER_REGISTER_FAIL'
export const USER_CUSTOMER_REGISTER_RESET = 'USER_CUSTOMER_REGISTER_RESET'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const USER_VENDOR_REGISTER_REQUEST = 'USER_VENDOR_REGISTER_REQUEST'
export const USER_VENDOR_REGISTER_SUCCESS = 'USER_VENDOR_REGISTER_SUCCESS'
export const USER_VENDOR_REGISTER_FAIL = 'USER_VENDOR_REGISTER_FAIL'
export const USER_VENDOR_REGISTER_RESET = 'USER_VENDOR_REGISTER_RESET'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_CUSTOMER_UPDATE_REQUEST = 'USER_CUSTOMER_UPDATE_REQUEST'
export const USER_CUSTOMER_UPDATE_SUCCESS = 'USER_CUSTOMER_UPDATE_SUCCESS'
export const USER_CUSTOMER_UPDATE_FAIL = 'USER_CUSTOMER_UPDATE_FAIL'
export const USER_CUSTOMER_UPDATE_RESET = 'USER_CUSTOMER_UPDATE_RESET'

export const NEW_TEACHER_REQUEST = 'NEW_TEACHER_REQUEST'
export const NEW_TEACHER_SUCCESS = 'NEW_TEACHER_SUCCESS'
export const NEW_TEACHER_FAIL = 'NEW_TEACHER_FAIL'
export const NEW_TEACHER_RESET = 'NEW_TEACHER_RESET'

export const USER_TEACHER_UPDATE_REQUEST = 'USER_TEACHER_UPDATE_REQUEST'
export const USER_TEACHER_UPDATE_SUCCESS = 'USER_TEACHER_UPDATE_SUCCESS'
export const USER_TEACHER_UPDATE_FAIL = 'USER_TEACHER_UPDATE_FAIL'
export const USER_TEACHER_UPDATE_RESET = 'USER_TEACHER_UPDATE_RESET'

export const INDIVIDUAL_TEACHER_REQUEST = 'INDIVIDUAL_TEACHER_REQUEST'
export const INDIVIDUAL_TEACHER_SUCCESS = 'INDIVIDUAL_TEACHER_SUCCESS'
export const INDIVIDUAL_TEACHER_FAIL = 'INDIVIDUAL_TEACHER_FAIL'
export const INDIVIDUAL_TEACHER_RESET = 'INDIVIDUAL_TEACHER_RESET'

export const PARENT_REQUEST = 'PARENT_REQUEST'
export const PARENT_SUCCESS = 'PARENT_SUCCESS'
export const PARENT_FAIL = 'PARENT_FAIL'
export const PARENT_RESET = 'PARENT_RESET'

export const NEW_PARENT_REQUEST = 'NEW_PARENT_REQUEST'
export const NEW_PARENT_SUCCESS = 'NEW_PARENT_SUCCESS'
export const NEW_PARENT_FAIL = 'NEW_PARENT_FAIL'
export const NEW_PARENT_RESET = 'NEW_PARENT_RESET'

export const USER_PARENT_UPDATE_REQUEST = 'USER_PARENT_UPDATE_REQUEST'
export const USER_PARENT_UPDATE_SUCCESS = 'USER_PARENT_UPDATE_SUCCESS'
export const USER_PARENT_UPDATE_FAIL = 'USER_PARENT_UPDATE_FAIL'
export const USER_PARENT_UPDATE_RESET = 'USER_PARENT_UPDATE_RESET'

export const INDIVIDUAL_PARENT_REQUEST = 'INDIVIDUAL_PARENT_REQUEST'
export const INDIVIDUAL_PARENT_SUCCESS = 'INDIVIDUAL_PARENT_SUCCESS'
export const INDIVIDUAL_PARENT_FAIL = 'INDIVIDUAL_PARENT_FAIL'
export const INDIVIDUAL_PARENT_RESET = 'INDIVIDUAL_PARENT_RESET'

export const INDIVIDUAL_CHILDREN_REQUEST = 'INDIVIDUAL_CHILDREN_REQUEST'
export const INDIVIDUAL_CHILDREN_SUCCESS = 'INDIVIDUAL_CHILDREN_SUCCESS'
export const INDIVIDUAL_CHILDREN_FAIL = 'INDIVIDUAL_CHILDREN_FAIL'
export const INDIVIDUAL_CHILDREN_RESET = 'INDIVIDUAL_CHILDREN_RESET'

export const INDIVIDUAL_RESULT_REQUEST = 'INDIVIDUAL_RESULT_REQUEST'
export const INDIVIDUAL_RESULT_SUCCESS = 'INDIVIDUAL_RESULT_SUCCESS'
export const INDIVIDUAL_RESULT_FAIL = 'INDIVIDUAL_RESULT_FAIL'
export const INDIVIDUAL_RESULT_RESET = 'INDIVIDUAL_RESULT_RESET'

export const CHILDREN_DEMOGRAPHIC_GENDER_REQUEST = 'CHILDREN_DEMOGRAPHIC_GENDER_REQUEST'
export const CHILDREN_DEMOGRAPHIC_GENDER_SUCCESS = 'CHILDREN_DEMOGRAPHIC_GENDER_SUCCESS'
export const CHILDREN_DEMOGRAPHIC_GENDER_FAIL = 'CHILDREN_DEMOGRAPHIC_GENDER_FAIL'
export const CHILDREN_DEMOGRAPHIC_GENDER_RESET = 'CHILDREN_DEMOGRAPHIC_GENDER_RESET'

export const CHILDREN_DETAILS_REQUEST = 'CHILDREN_DETAILS_REQUEST'
export const CHILDREN_DETAILS_SUCCESS = 'CHILDREN_DETAILS_SUCCESS'
export const CHILDREN_DETAILS_FAIL = 'CHILDREN_DETAILS_FAIL'
export const CHILDREN_DETAILS_RESET = 'CHILDREN_DETAILS_RESET'

export const CHILDREN_ADD_REQUEST = 'CHILDREN_ADD_REQUEST'
export const CHILDREN_ADD_SUCCESS = 'CHILDREN_ADD_SUCCESS'
export const CHILDREN_ADD_FAIL = 'CHILDREN_ADD_FAIL'
export const CHILDREN_ADD_RESET = 'CHILDREN_ADD_RESET'

export const CHILDREN_UPDATE_REQUEST = 'CHILDREN_UPDATE_REQUEST'
export const CHILDREN_UPDATE_SUCCESS = 'CHILDREN_UPDATE_SUCCESS'
export const CHILDREN_UPDATE_FAIL = 'CHILDREN_UPDATE_FAIL'
export const CHILDREN_UPDATE_RESET = 'CHILDREN_UPDATE_RESET'

export const CHILDREN_DELETE_REQUEST = 'CHILDREN_DELETE_REQUEST'
export const CHILDREN_DELETE_SUCCESS = 'CHILDREN_DELETE_SUCCESS'
export const CHILDREN_DELETE_FAIL = 'CHILDREN_DELETE_FAIL'
export const CHILDREN_DELETE_RESET = 'CHILDREN_DELETE_RESET'

export const GLOBAL_RANKING_REQUEST = 'GLOBAL_RANKING_REQUEST'
export const GLOBAL_RANKING_SUCCESS = 'GLOBAL_RANKING_SUCCESS'
export const GLOBAL_RANKING_FAIL = 'GLOBAL_RANKING_FAIL'
export const GLOBAL_RANKING_RESET = 'GLOBAL_RANKING_RESET'

export const CLASS_RANKING_REQUEST = 'CLASS_RANKING_REQUEST'
export const CLASS_RANKING_SUCCESS = 'CLASS_RANKING_SUCCESS'
export const CLASS_RANKING_FAIL = 'CLASS_RANKING_FAIL'
export const CLASS_RANKING_RESET = 'CLASS_RANKING_RESET'

export const CLASS_COMPARISION_REQUEST = 'CLASS_COMPARISION_REQUEST'
export const CLASS_COMPARISION_SUCCESS = 'CLASS_COMPARISION_SUCCESS'
export const CLASS_COMPARISION_FAIL = 'CLASS_COMPARISION_FAIL'
export const CLASS_COMPARISION_RESET = 'CLASS_COMPARISION_RESET'

export const NOTICATION_REQUEST = 'NOTICATION_REQUEST'
export const NOTICATION_SUCCESS = 'NOTICATION_SUCCESS'
export const NOTICATION_FAIL = 'NOTICATION_FAIL'
export const NOTICATION_RESET = 'NOTICATION_RESET'

export const NEW_NOTICATION_REQUEST = 'NEW_NOTICATION_REQUEST'
export const NEW_NOTICATION_SUCCESS = 'NEW_NOTICATION_SUCCESS'
export const NEW_NOTICATION_FAIL = 'NEW_NOTICATION_FAIL'
export const NEW_NOTICATION_RESET = 'NEW_NOTICATION_RESET'