export const ANNOUNCEMENT_REQUEST = 'ANNOUNCEMENT_REQUEST'
export const ANNOUNCEMENT_SUCCESS = 'ANNOUNCEMENT_SUCCESS'
export const ANNOUNCEMENT_RESET = 'ANNOUNCEMENT_RESET'
export const ANNOUNCEMENT_FAIL = 'ANNOUNCEMENT_FAIL'