export const GET_CLASS_REQUEST = "GET_CLASS_REQUEST"
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS"
export const GET_CLASS_FAIL = "GET_CLASS_FAIL"
export const GET_CLASS_RESET = "GET_CLASS_RESET"

export const GET_CHILDREN_REQUEST = "GET_CHILDREN_REQUEST"
export const GET_CHILDREN_SUCCESS = "GET_CHILDREN_SUCCESS"
export const GET_CHILDREN_FAIL = "GET_CHILDREN_FAIL"
export const GET_CHILDREN_RESET = "GET_CHILDREN_RESET"

export const INDIVIDUAL_CHILDREN_REQUEST = "INDIVIDUAL_CHILDREN_REQUEST"
export const INDIVIDUAL_CHILDREN_SUCCESS = "INDIVIDUAL_CHILDREN_SUCCESS"
export const INDIVIDUAL_CHILDREN_FAIL = "INDIVIDUAL_CHILDREN_FAIL"
export const INDIVIDUAL_CHILDREN_RESET = "INDIVIDUAL_CHILDREN_RESET"

export const UPDATE_CHILDREN_REQUEST = "UPDATE_CHILDREN_REQUEST"
export const UPDATE_CHILDREN_SUCCESS = "UPDATE_CHILDREN_SUCCESS"
export const UPDATE_CHILDREN_FAIL = "UPDATE_CHILDREN_FAIL"
export const UPDATE_CHILDREN_RESET = "UPDATE_CHILDREN_RESET"

export const GET_PARENT_REQUEST = "GET_PARENT_REQUEST"
export const GET_PARENT_SUCCESS = "GET_PARENT_SUCCESS"
export const GET_PARENT_FAIL = "GET_PARENT_FAIL"
export const GET_PARENT_RESET = "GET_PARENT_RESET"

export const SUBJECT_REQUEST = "SUBJECT_REQUEST"
export const SUBJECT_SUCCESS = "SUBJECT_SUCCESS"
export const SUBJECT_FAIL = "SUBJECT_FAIL"
export const SUBJECT_RESET = "SUBJECT_RESET"

export const SUBJECT_GRADE_REQUEST = "SUBJECT_GRADE_REQUEST"
export const SUBJECT_GRADE_SUCCESS = "SUBJECT_GRADE_SUCCESS"
export const SUBJECT_GRADE_FAIL = "SUBJECT_GRADE_FAIL"
export const SUBJECT_GRADE_RESET = "SUBJECT_GRADE_RESET"

export const NEW_SUBJECT_GRADE_REQUEST = "NEW_SUBJECT_GRADE_REQUEST"
export const NEW_SUBJECT_GRADE_SUCCESS = "NEW_SUBJECT_GRADE_SUCCESS"
export const NEW_SUBJECT_GRADE_FAIL = "NEW_SUBJECT_GRADE_FAIL"
export const NEW_SUBJECT_GRADE_RESET = "NEW_SUBJECT_GRADE_RESET"

export const UPDATE_SUBJECT_GRADE_REQUEST = "UPDATE_SUBJECT_GRADE_REQUEST"
export const UPDATE_SUBJECT_GRADE_SUCCESS = "UPDATE_SUBJECT_GRADE_SUCCESS"
export const UPDATE_SUBJECT_GRADE_FAIL = "UPDATE_SUBJECT_GRADE_FAIL"
export const UPDATE_SUBJECT_GRADE_RESET = "UPDATE_SUBJECT_GRADE_RESET"

export const DELETE_SUBJECT_GRADE_REQUEST = "DELETE_SUBJECT_GRADE_REQUEST"
export const DELETE_SUBJECT_GRADE_SUCCESS = "DELETE_SUBJECT_GRADE_SUCCESS"
export const DELETE_SUBJECT_GRADE_FAIL = "DELETE_SUBJECT_GRADE_FAIL"
export const DELETE_SUBJECT_GRADE_RESET = "DELETE_SUBJECT_GRADE_RESET"

export const CLASS_RANKING_REQUEST = "CLASS_RANKING_REQUEST"
export const CLASS_RANKING_SUCCESS = "CLASS_RANKING_SUCCESS"
export const CLASS_RANKING_FAIL = "CLASS_RANKING_FAIL"
export const CLASS_RANKING_RESET = "CLASS_RANKING_RESET"

export const GLOBAL_RANKING_REQUEST = "GLOBAL_RANKING_REQUEST"
export const GLOBAL_RANKING_SUCCESS = "GLOBAL_RANKING_SUCCESS"
export const GLOBAL_RANKING_FAIL = "GLOBAL_RANKING_FAIL"
export const GLOBAL_RANKING_RESET = "GLOBAL_RANKING_RESET"

