export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_FORGET_REQUEST = 'USER_FORGET_REQUEST'
export const USER_FORGET_SUCCESS = 'USER_FORGET_SUCCESS'
export const USER_FORGET_RESET = 'USER_FORGET_RESET'
export const USER_FORGET_FAIL = 'USER_FORGET_FAIL'