export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_FORGET_REQUEST = 'USER_FORGET_REQUEST'
export const USER_FORGET_SUCCESS = 'USER_FORGET_SUCCESS'
export const USER_FORGET_RESET = 'USER_FORGET_RESET'
export const USER_FORGET_FAIL = 'USER_FORGET_FAIL'


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'


export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const SCANNER_REQUEST = "SCANNER_REQUEST"
export const SCANNER_SUCCESS = "SCANNER_SUCCESS"
export const SCANNER_FAIL = "SCANNER_FAIL"
export const SCANNER_RESET = "SCANNER_RESET"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"
export const LOGOUT_RESET = "LOGOUT_RESET"

export const NEW_ATTENDANCE_REQUEST = "NEW_ATTENDANCE_REQUEST"
export const NEW_ATTENDANCE_SUCCESS = "NEW_ATTENDANCE_SUCCESS"
export const NEW_ATTENDANCE_FAIL = "NEW_ATTENDANCE_FAIL"
export const NEW_ATTENDANCE_RESET = "NEW_ATTENDANCE_RESET"