# Generated by Django 3.2.5 on 2023-01-10 14:47

import EZkidsApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcementID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('announcement', models.CharField(blank=True, max_length=2500)),
                ('announcementTime', models.DateTimeField(auto_now_add=True)),
                ('announcementSchedule', models.DateTimeField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('childFirstName', models.CharField(blank=True, max_length=128)),
                ('childLastName', models.CharField(blank=True, max_length=128)),
                ('childID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('childDOB', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parentsID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parentsType', models.CharField(blank=True, choices=[('M', 'Mother'), ('F', 'Father'), ('G', 'Guardian')], max_length=1)),
                ('parentsFirstName', models.CharField(blank=True, max_length=128)),
                ('parentsLastName', models.CharField(blank=True, max_length=128)),
                ('parentsContactphone', models.TextField(blank=True, max_length=16)),
                ('parentsEmail', models.EmailField(max_length=320, unique=True)),
                ('secondParentEmail', models.EmailField(max_length=320, unique=True)),
                ('parentsAddress', models.TextField(blank=True, max_length=200)),
                ('parentsDOB', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['parentsID'],
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('principalID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['principalID'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('Last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_principal', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('todoID', models.TextField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=EZkidsApp.models.one_week_hence)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.todolist')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('teacherFirstName', models.CharField(blank=True, max_length=128)),
                ('teacherLastName', models.CharField(blank=True, max_length=128)),
                ('teacherEmail', models.EmailField(max_length=320, unique=True)),
                ('teacherContactphone', models.TextField(blank=True, max_length=16)),
                ('bankAccountHolder', models.CharField(max_length=100)),
                ('teacherBankName', models.CharField(max_length=100)),
                ('teacherBankAcc', models.CharField(max_length=16)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacherID'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('subject_gradeID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.children')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.parent')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homeworkID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.children')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('className', models.CharField(blank=True, max_length=16)),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.children')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='children',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.parent'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('attendance', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.children')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.parent')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.subject')),
            ],
        ),
    ]
