# Generated by Django 3.2.5 on 2023-01-10 15:11

import EZkidsApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='children',
        ),
        migrations.AddField(
            model_name='children',
            name='class_belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EZkidsApp.class'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcementID',
            field=models.CharField(default=EZkidsApp.models.Announcement.generate_announcement_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendanceID',
            field=models.CharField(default=EZkidsApp.models.Attendance.generate_attendance_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='childID',
            field=models.CharField(default=EZkidsApp.models.Children.generate_child_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='classID',
            field=models.CharField(default=EZkidsApp.models.Class.generate_class_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homeworkID',
            field=models.CharField(default=EZkidsApp.models.Homework.generate_homework_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parentsID',
            field=models.CharField(default=EZkidsApp.models.Parent.generate_parent_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectID',
            field=models.CharField(default=EZkidsApp.models.Subject.generate_subject_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectgrade',
            name='subject_gradeID',
            field=models.CharField(default=EZkidsApp.models.SubjectGrade.generate_grade_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherID',
            field=models.CharField(default=EZkidsApp.models.Teacher.generate_teacher_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todoID',
            field=models.TextField(default=EZkidsApp.models.ToDoItem.generate_todo_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(default=EZkidsApp.models.User.generate_user_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
