# Generated by Django 3.2.5 on 2023-01-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0005_alter_subjectgrade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homeworkDesc',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='homework',
            name='homeworkTitle',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
