# Generated by Django 3.2.5 on 2023-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0007_auto_20230126_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement',
            new_name='announcementTitle',
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcementDesc',
            field=models.CharField(blank=True, max_length=5500),
        ),
    ]
