# Generated by Django 3.2.5 on 2023-01-30 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0008_auto_20230130_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgrade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EZkidsApp.subject'),
        ),
    ]
