# Generated by Django 3.2.5 on 2023-01-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0010_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('created_date', 'children', 'subject')},
        ),
    ]
