# Generated by Django 3.2.5 on 2023-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0013_auto_20230201_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcementSchedule',
            field=models.DateTimeField(blank=True, max_length=2500, null=True),
        ),
    ]
