# Generated by Django 3.2.5 on 2023-02-10 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0015_alter_announcement_announcementtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcementTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
