# Generated by Django 3.2.5 on 2023-02-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0017_alter_announcement_announcementtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcementTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
