# Generated by Django 3.2.5 on 2023-02-10 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0018_alter_announcement_announcementtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcementSchedule',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=2500),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcementTime',
            field=models.DateTimeField(),
        ),
    ]
