# Generated by Django 3.2.5 on 2023-02-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0020_auto_20230219_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankName',
        ),
    ]
