# Generated by Django 3.2.5 on 2023-02-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZkidsApp', '0021_delete_bankname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankName',
            fields=[
                ('bankID', models.CharField(default=1, editable=False, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('bankName', models.TextField(max_length=100)),
            ],
        ),
    ]
